# Generated by Django 2.2 on 2021-05-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall_message',
            name='likes',
            field=models.ManyToManyField(related_name='liked_posts', to='wall_app.User'),
        ),
    ]
